// flow-typed signature: 787ddbd0c4aaf7c6ba02fc8574717947
// flow-typed version: <<STUB>>/fastify-multipart_v0.5.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-multipart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify-multipart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify-multipart/example' {
  declare module.exports: any;
}

declare module 'fastify-multipart/test' {
  declare module.exports: any;
}

declare module 'fastify-multipart/tester' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify-multipart/example.js' {
  declare module.exports: $Exports<'fastify-multipart/example'>;
}
declare module 'fastify-multipart/index' {
  declare module.exports: $Exports<'fastify-multipart'>;
}
declare module 'fastify-multipart/index.js' {
  declare module.exports: $Exports<'fastify-multipart'>;
}
declare module 'fastify-multipart/test.js' {
  declare module.exports: $Exports<'fastify-multipart/test'>;
}
declare module 'fastify-multipart/tester.js' {
  declare module.exports: $Exports<'fastify-multipart/tester'>;
}
