// flow-typed signature: af54f3466b39941e90f37f1645a1b054
// flow-typed version: <<STUB>>/fastify-no-icon_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-no-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify-no-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify-no-icon/plugin' {
  declare module.exports: any;
}

declare module 'fastify-no-icon/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify-no-icon/plugin.js' {
  declare module.exports: $Exports<'fastify-no-icon/plugin'>;
}
declare module 'fastify-no-icon/test.js' {
  declare module.exports: $Exports<'fastify-no-icon/test'>;
}
