// flow-typed signature: c0d7d0799ec74a2fa1a59aabcfba3862
// flow-typed version: <<STUB>>/fastify-sensible_v0.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-sensible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify-sensible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify-sensible/lib/assert' {
  declare module.exports: any;
}

declare module 'fastify-sensible/lib/httpErrors' {
  declare module.exports: any;
}

declare module 'fastify-sensible/lib/vary' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/assert.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/errorHandler.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/forwarded.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/httpErrors.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/httpErrorsReply.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/is.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/proxyaddr.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/to.test' {
  declare module.exports: any;
}

declare module 'fastify-sensible/test/vary.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify-sensible/index' {
  declare module.exports: $Exports<'fastify-sensible'>;
}
declare module 'fastify-sensible/index.js' {
  declare module.exports: $Exports<'fastify-sensible'>;
}
declare module 'fastify-sensible/lib/assert.js' {
  declare module.exports: $Exports<'fastify-sensible/lib/assert'>;
}
declare module 'fastify-sensible/lib/httpErrors.js' {
  declare module.exports: $Exports<'fastify-sensible/lib/httpErrors'>;
}
declare module 'fastify-sensible/lib/vary.js' {
  declare module.exports: $Exports<'fastify-sensible/lib/vary'>;
}
declare module 'fastify-sensible/test/assert.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/assert.test'>;
}
declare module 'fastify-sensible/test/errorHandler.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/errorHandler.test'>;
}
declare module 'fastify-sensible/test/forwarded.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/forwarded.test'>;
}
declare module 'fastify-sensible/test/httpErrors.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/httpErrors.test'>;
}
declare module 'fastify-sensible/test/httpErrorsReply.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/httpErrorsReply.test'>;
}
declare module 'fastify-sensible/test/is.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/is.test'>;
}
declare module 'fastify-sensible/test/proxyaddr.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/proxyaddr.test'>;
}
declare module 'fastify-sensible/test/to.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/to.test'>;
}
declare module 'fastify-sensible/test/vary.test.js' {
  declare module.exports: $Exports<'fastify-sensible/test/vary.test'>;
}
