// flow-typed signature: c2c89556bd0eb96a144b657b93445682
// flow-typed version: <<STUB>>/tpl-lib-helpers_v^0.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tpl-lib-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tpl-lib-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tpl-lib-helpers/config/babel' {
  declare module.exports: any;
}

declare module 'tpl-lib-helpers/config/jest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tpl-lib-helpers/config/babel.js' {
  declare module.exports: $Exports<'tpl-lib-helpers/config/babel'>;
}
declare module 'tpl-lib-helpers/config/jest.js' {
  declare module.exports: $Exports<'tpl-lib-helpers/config/jest'>;
}
declare module 'tpl-lib-helpers/index' {
  declare module.exports: $Exports<'tpl-lib-helpers'>;
}
declare module 'tpl-lib-helpers/index.js' {
  declare module.exports: $Exports<'tpl-lib-helpers'>;
}
