// flow-typed signature: 84a1abedc42aa55caf7b58a8215905ae
// flow-typed version: <<STUB>>/tpl-api-helpers_v^0.3.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tpl-api-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tpl-api-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tpl-api-helpers/config/babel' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/config/jest' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/config/sequelize' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/fastify/index' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/fastify/plugin/routes' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/fastify/plugin/sequelize' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/util/index' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/util/log' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/util/sequelize/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tpl-api-helpers/config/babel.js' {
  declare module.exports: $Exports<'tpl-api-helpers/config/babel'>;
}
declare module 'tpl-api-helpers/config/jest.js' {
  declare module.exports: $Exports<'tpl-api-helpers/config/jest'>;
}
declare module 'tpl-api-helpers/config/sequelize.js' {
  declare module.exports: $Exports<'tpl-api-helpers/config/sequelize'>;
}
declare module 'tpl-api-helpers/fastify/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers/fastify/index'>;
}
declare module 'tpl-api-helpers/fastify/plugin/routes.js' {
  declare module.exports: $Exports<'tpl-api-helpers/fastify/plugin/routes'>;
}
declare module 'tpl-api-helpers/fastify/plugin/sequelize.js' {
  declare module.exports: $Exports<'tpl-api-helpers/fastify/plugin/sequelize'>;
}
declare module 'tpl-api-helpers/index' {
  declare module.exports: $Exports<'tpl-api-helpers'>;
}
declare module 'tpl-api-helpers/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers'>;
}
declare module 'tpl-api-helpers/util/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers/util/index'>;
}
declare module 'tpl-api-helpers/util/log.js' {
  declare module.exports: $Exports<'tpl-api-helpers/util/log'>;
}
declare module 'tpl-api-helpers/util/sequelize/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers/util/sequelize/index'>;
}
